### PR TITLE
Updated the SSCS Cover Letter

### PR DESCRIPTION
**Pull request by ss-evoco**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by mdayican — COMMENTED** [review]
have you upload them to docmosis?

**Comment by hajam09** [comment]
I have the PR ready on docmosis. Perhaps I can merge both this and the other pr simultaneously?

**Comment by mdayican** [comment]
> I have the PR ready on docmosis. Perhaps I can merge both this and the other pr simultaneously?

we have problem in master pipeline waiting Plat-ops to solve it, I will approve and merge when it is solved.

**Comment by hajam09** [comment]
No worries. Can you immediately notify me once approved and merged, so that I can merge the docmosis change as well. Thanks

**Review by mdayican — APPROVED** [review]

**Pull request merged**
